/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuiaGenogramaRouteImport } from './routes/guia-genograma'
import { Route as IndexRouteImport } from './routes/index'

const GuiaGenogramaRoute = GuiaGenogramaRouteImport.update({
  id: '/guia-genograma',
  path: '/guia-genograma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guia-genograma': typeof GuiaGenogramaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guia-genograma': typeof GuiaGenogramaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guia-genograma': typeof GuiaGenogramaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guia-genograma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guia-genograma'
  id: '__root__' | '/' | '/guia-genograma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiaGenogramaRoute: typeof GuiaGenogramaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guia-genograma': {
      id: '/guia-genograma'
      path: '/guia-genograma'
      fullPath: '/guia-genograma'
      preLoaderRoute: typeof GuiaGenogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiaGenogramaRoute: GuiaGenogramaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
