import type { Gender } from "./types.ts";

const MALE = new Set(
  [
    "juan",
    "jose",
    "josé",
    "pedro",
    "carlos",
    "miguel",
    "antonio",
    "francisco",
    "david",
    "jorge",
    "luis",
    "manuel",
    "rafael",
    "angel",
    "ángel",
    "pablo",
    "daniel",
    "andres",
    "andrés",
    "sergio",
    "javier",
    "alberto",
    "fernando",
    "ricardo",
    "diego",
    "mario",
    "oscar",
    "óscar",
    "enrique",
    "raul",
    "raúl",
    "victor",
    "víctor",
    "hugo",
    "ivan",
    "iván",
    "adrian",
    "adrián",
    "martin",
    "martín",
    "alejandro",
    "eduardo",
    "roberto",
    "ramon",
    "ramón",
    "tomas",
    "tomás",
    "samuel",
    "gabriel",
    "ignacio",
    "hector",
    "héctor",
    "felipe",
    "cesar",
    "césar",
    "julian",
    "julián",
    "emilio",
    "nicolas",
    "nicolás",
    "sebastian",
    "sebastián",
    "esteban",
    "guillermo",
    "rodrigo",
    "alvaro",
    "álvaro",
    "paco",
    "pepe",
    "lolo",
    "nacho",
    "manolo",
    "jesus",
    "jesús",
    "salvador",
    "agustin",
    "agustín",
    "benito",
    "lorenzo",
    "marcos",
    "mateo",
    "santiago",
    "joaquin",
    "joaquín",
    "arturo",
    "ruben",
    "rubén",
    "ismael",
    "bruno",
    "leonardo",
    "maximiliano",
    "emmanuel",
  ].map((n) => n.toLowerCase()),
);

const FEMALE = new Set(
  [
    "maria",
    "maría",
    "carmen",
    "laura",
    "ana",
    "sofia",
    "sofía",
    "lucia",
    "lucía",
    "elena",
    "marta",
    "patricia",
    "isabel",
    "cristina",
    "pilar",
    "rosa",
    "teresa",
    "paula",
    "andrea",
    "alicia",
    "beatriz",
    "nuria",
    "silvia",
    "monica",
    "mónica",
    "raquel",
    "irene",
    "claudia",
    "sara",
    "nerea",
    "ainhoa",
    "julia",
    "carla",
    "natalia",
    "angela",
    "ángela",
    "lorena",
    "veronica",
    "verónica",
    "inés",
    "ines",
    "esther",
    "eva",
    "gloria",
    "dolores",
    "lola",
    "concepcion",
    "concepción",
    "mercedes",
    "francisca",
    "antonia",
    "josefa",
    "encarnacion",
    "encarnación",
    "amparo",
    "remedios",
    "soledad",
    "rocio",
    "rocío",
    "esperanza",
    "consuelo",
    "milagros",
    "asuncion",
    "asunción",
    "adriana",
    "valeria",
    "camila",
    "valentina",
    "daniela",
    "martina",
    "emilia",
    "catalina",
    "fernanda",
    "gabriela",
    "alejandra",
    "monica",
    "olga",
    "yolanda",
    "susana",
    "pilar",
    "blanca",
    "natividad",
    "magdalena",
    "elvira",
    "amelia",
    "victoria",
    "paloma",
    "noelia",
    "marina",
    "lidia",
    "sonia",
    "miriam",
    "miríam",
    "ainara",
    "leire",
    "maite",
    "itziar",
  ].map((n) => n.toLowerCase()),
);

export function inferGenderFromName(name: string, fallback: Gender = "unknown"): Gender {
  const key = name.trim().toLowerCase();
  const first = key.split(/\s+/)[0] ?? key;
  if (MALE.has(key) || MALE.has(first)) return "male";
  if (FEMALE.has(key) || FEMALE.has(first)) return "female";
  if (first.endsWith("o") && !first.endsWith("ao")) {
    // weak heuristic — skip
  }
  return fallback;
}

export function genderFromWord(word: string): Gender | null {
  const w = word.toLowerCase();
  if (
    /casada|esposa|mujer|madre|hermana|hija|tía|tia|abuela|nieta|nuera|prima|señora|sra/.test(
      w,
    )
  ) {
    return "female";
  }
  if (
    /casado|esposo|marido|hombre|padre|hermano|hijo|tío|tio|abuelo|nieto|yerno|primo|señor|sr/.test(
      w,
    )
  ) {
    return "male";
  }
  return null;
}
