import type { Gender } from "./types.ts";

const MALE = new Set(
  [
    "camilo",
    "edgar",
    "oliver",
    "oliverio",
    "yeison",
    "jhon",
    "john",
    "brayan",
    "kevin",
    "wilson",
    "fabio",
    "jairo",
    "harold",
    "cristian",
    "christian",
    "duvan",
    "nestor",
    "néstor",
    "alexander",
    "juan",
    "jose",
    "josé",
    "pedro",
    "carlos",
    "miguel",
    "antonio",
    "francisco",
    "david",
    "jorge",
    "luis",
    "manuel",
    "rafael",
    "angel",
    "ángel",
    "pablo",
    "daniel",
    "andres",
    "andrés",
    "sergio",
    "javier",
    "alberto",
    "fernando",
    "ricardo",
    "diego",
    "mario",
    "oscar",
    "óscar",
    "enrique",
    "raul",
    "raúl",
    "victor",
    "víctor",
    "hugo",
    "ivan",
    "iván",
    "adrian",
    "adrián",
    "martin",
    "martín",
    "alejandro",
    "eduardo",
    "roberto",
    "ramon",
    "ramón",
    "tomas",
    "tomás",
    "samuel",
    "gabriel",
    "ignacio",
    "hector",
    "héctor",
    "felipe",
    "cesar",
    "césar",
    "julian",
    "julián",
    "emilio",
    "nicolas",
    "nicolás",
    "sebastian",
    "sebastián",
    "esteban",
    "guillermo",
    "rodrigo",
    "alvaro",
    "álvaro",
    "paco",
    "pepe",
    "lolo",
    "nacho",
    "manolo",
    "jesus",
    "jesús",
    "salvador",
    "agustin",
    "agustín",
    "benito",
    "lorenzo",
    "marcos",
    "mateo",
    "santiago",
    "joaquin",
    "joaquín",
    "arturo",
    "ruben",
    "rubén",
    "ismael",
    "bruno",
    "leonardo",
    "maximiliano",
    "emmanuel",
  ].map((n) => n.toLowerCase()),
);

const FEMALE = new Set(
  [
    "marinella",
    "yaneth",
    "yanet",
    "judith",
    "yesica",
    "jessica",
    "yuliana",
    "paola",
    "sandra",
    "diana",
    "liliana",
    "luz",
    "martha",
    "carolina",
    "viviana",
    "isabella",
    "mariana",
    "johana",
    "nubia",
    "maria",
    "maría",
    "carmen",
    "laura",
    "ana",
    "sofia",
    "sofía",
    "lucia",
    "lucía",
    "elena",
    "marta",
    "patricia",
    "isabel",
    "cristina",
    "pilar",
    "rosa",
    "teresa",
    "paula",
    "andrea",
    "alicia",
    "beatriz",
    "nuria",
    "silvia",
    "monica",
    "mónica",
    "raquel",
    "irene",
    "claudia",
    "sara",
    "nerea",
    "ainhoa",
    "julia",
    "carla",
    "natalia",
    "angela",
    "ángela",
    "lorena",
    "veronica",
    "verónica",
    "inés",
    "ines",
    "esther",
    "eva",
    "gloria",
    "dolores",
    "lola",
    "concepcion",
    "concepción",
    "mercedes",
    "francisca",
    "antonia",
    "josefa",
    "encarnacion",
    "encarnación",
    "amparo",
    "remedios",
    "soledad",
    "rocio",
    "rocío",
    "esperanza",
    "consuelo",
    "milagros",
    "asuncion",
    "asunción",
    "adriana",
    "valeria",
    "camila",
    "valentina",
    "daniela",
    "martina",
    "emilia",
    "catalina",
    "fernanda",
    "gabriela",
    "alejandra",
    "monica",
    "olga",
    "yolanda",
    "susana",
    "pilar",
    "blanca",
    "natividad",
    "magdalena",
    "elvira",
    "amelia",
    "victoria",
    "paloma",
    "noelia",
    "marina",
    "lidia",
    "sonia",
    "miriam",
    "miríam",
    "ainara",
    "leire",
    "maite",
    "itziar",
  ].map((n) => n.toLowerCase()),
);

export function inferGenderFromName(name: string, fallback: Gender = "unknown"): Gender {
  const key = name.trim().toLowerCase();
  const first = key.split(/\s+/)[0] ?? key;
  if (MALE.has(key) || MALE.has(first)) return "male";
  if (FEMALE.has(key) || FEMALE.has(first)) return "female";
  if (first.endsWith("o") && !first.endsWith("ao")) {
    // weak heuristic — skip
  }
  return fallback;
}

const WORD_START = "(?<![\\p{L}])";
const WORD_END = "(?![\\p{L}])";
const FEMALE_WORDS = new RegExp(
  `${WORD_START}(?:casadas?|esposas?|mujer(?:es)?|madres?|hermanas?|hijas?|t[ií]as?|abuelas?|nietas?|nueras?|primas?|se[nñ]oras?|sras?|novias?|viudas?|divorciadas?|separadas?|adoptadas?|ni[nñ]as?|chicas?|exesposas?|fallecidas?)${WORD_END}`,
  "iu",
);
const MALE_WORDS = new RegExp(
  `${WORD_START}(?:casados?|esposos?|maridos?|hombres?|var[oó]n(?:es)?|padres?|hermanos?|hijos?|t[ií]os?|abuelos?|nietos?|yernos?|primos?|se[nñ]ores?|sres?|novios?|viudos?|divorciados?|separados?|adoptados?|ni[nñ]os?|chicos?|exesposos?|exmaridos?|fallecidos?)${WORD_END}`,
  "iu",
);

export function genderFromWord(word: string): Gender | null {
  if (FEMALE_WORDS.test(word)) return "female";
  if (MALE_WORDS.test(word)) return "male";
  return null;
}
